# Numerik Blatt 01

___________________

#### Von
* Ege Cabuk

#### b)
   $b_i = Ax = \sum_{j=1}^{n}x_j a_j$

#### c)

In [ ]:
#Das ist ein Kommentar in Python!

#### d)

In [31]:
import numpy as np

array1 = [1, 2, 3, 4]

vektor1 = np.array(array1)
  
print("1 x 4 Zeilen Vektor: ", vektor1)

1 x 4 ZeilenVektor:  [1 2 3 4]


#### e)

In [32]:
import numpy as np

array2 = [[1],
           [2],
           [3],
           [4],
           [5]]

vektor2 = np.array(array2)
  
print("5 x 1 Zeilen Vektor: ", vektor2)

5 x 1 ZeilenVektor:  [[1]
 [2]
 [3]
 [4]
 [5]]


#### f)

In [26]:
import numpy as np

matrix_3d = np.zeros((3,3))
print(matrix_3d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### g)

In [27]:
import numpy as np

#Zum zeigen einfach eine Nullmatrix erstellt
matrix = np.zeros((4,3))
print(matrix[1])

[0. 0. 0.]


#### h)

In [28]:
import numpy as np

matrix = np.zeros((4,4))
print(matrix[2])

[0. 0. 0. 0.]


#### i)

In [34]:
import numpy as np

matrix = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
print(matrix.transpose())

[[21 11 43]
 [22 22 77]
 [23 33 89]]


#### j

In [38]:
import numpy as np

matrix1 = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
matrix2 = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
print(matrix1 * matrix2)

#Multiplikation
print(np.matmul(matrix1, matrix2))

[[ 441  484  529]
 [ 121  484 1089]
 [1849 5929 7921]]
[[ 1672  2717  3256]
 [ 1892  3267  3916]
 [ 5577  9493 11451]]


#### k)

In [54]:
import numpy as np

matrix1 = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
matrix2 = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
matrix3_c = np.c_[matrix2, matrix1]
matrix4_r = np.r_[matrix3, matrix3]
print("Spalten hinzugefügt: ")
print(matrix3_c)
print("_________________________________________________")
print("Zeilen hinzugefügt: ")
print(matrix4_r)

Spalten hinzugefügt: 
[[21 22 23 21 22 23]
 [11 22 33 11 22 33]
 [43 77 89 43 77 89]]
_________________________________________________
Zeilen hinzugefügt: 
[[21 22 23 21 22 23]
 [11 22 33 11 22 33]
 [43 77 89 43 77 89]
 [21 22 23 21 22 23]
 [11 22 33 11 22 33]
 [43 77 89 43 77 89]]


#### l)

In [52]:
import numpy as np

matrix1 = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))

#Zeigt die Dimension an
print(matrix1.shape)

(3, 3)


#### m)

In [61]:
import numpy as np

matrix1 = np.array(([11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33]))

print(matrix1.reshape(14,4))

[[11 22 33 43]
 [77 89 33 11]
 [22 33 43 77]
 [89 33 11 22]
 [33 43 77 89]
 [33 11 22 33]
 [43 77 89 33]
 [11 22 33 43]
 [77 89 33 11]
 [22 33 43 77]
 [89 33 11 22]
 [33 43 77 89]
 [33 11 22 33]
 [43 77 89 33]]


#### n)

In [69]:
import numpy as np

vektor1 = np.array([[1],
           [2],
           [3]])
vektor2= np.array([[1],
           [2],
           [3]])
for i in range(9999):
     vektor1 = np.c_[vektor1, vektor2]
    
print(vektor1)

[[1 1 1 ... 1 1 1]
 [2 2 2 ... 2 2 2]
 [3 3 3 ... 3 3 3]]


#### o)

In [77]:
import numpy as np

matrix1 = np.array(([-11, 22, 33, 43, 77, -89, 33],
                   [11, 22, 33, -43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, -22, 33, 43, -77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, -22, 33, -43, 77, 89, 33]))

for i in range(8):
    for j in range(7):
        #Kleiner null sollen 0 gesetzt werden
         if(matrix1[i][j]<0):
                matrix1[i][j] = 0
                
print(matrix1)
                

[[ 0 22 33 43 77  0 33]
 [11 22 33  0 77 89 33]
 [11 22 33 43 77 89 33]
 [11 22 33 43 77 89 33]
 [11  0 33 43  0 89 33]
 [11 22 33 43 77 89 33]
 [11 22 33 43 77 89 33]
 [11  0 33  0 77 89 33]]


#### p)

In [127]:
import numpy as np

matrix1 = np.array([[0]])
j = 0

for i in range(100):
    #Erster index soll 7 sein!
    if(i == 0):
        if(matrix1[0] == 0):
            matrix1[0] = 7
    
    if(i > 0):
        #Jetzt wird bis zu 7. Zahl gezählt
        j += 1
        if(j == 7):
            #Sobald 7 erreicht ist fangen wir an von vorne zu zählen
            j = 0;
            if(i != 7):
                matrix1 = np.r_[matrix1, [[i]]]
            
        
    

                

print(matrix1)
                

[[ 7]
 [14]
 [21]
 [28]
 [35]
 [42]
 [49]
 [56]
 [63]
 [70]
 [77]
 [84]
 [91]
 [98]]


#### q)

In [168]:
import numpy as np

matrix1 = np.array([[0]])
j = 0

for i in range(100):
     matrix1 = np.r_[matrix1, [[i]]]

for i in range(100):
    if(i == 0):
        matrix1[i][0] = i
    # Modulo 2 = 1 weil bei null beginnend
    if(i%2 == 1):
        matrix1[i][0] = 0
                
print(matrix1)

[[ 0]
 [ 0]
 [ 1]
 [ 0]
 [ 3]
 [ 0]
 [ 5]
 [ 0]
 [ 7]
 [ 0]
 [ 9]
 [ 0]
 [11]
 [ 0]
 [13]
 [ 0]
 [15]
 [ 0]
 [17]
 [ 0]
 [19]
 [ 0]
 [21]
 [ 0]
 [23]
 [ 0]
 [25]
 [ 0]
 [27]
 [ 0]
 [29]
 [ 0]
 [31]
 [ 0]
 [33]
 [ 0]
 [35]
 [ 0]
 [37]
 [ 0]
 [39]
 [ 0]
 [41]
 [ 0]
 [43]
 [ 0]
 [45]
 [ 0]
 [47]
 [ 0]
 [49]
 [ 0]
 [51]
 [ 0]
 [53]
 [ 0]
 [55]
 [ 0]
 [57]
 [ 0]
 [59]
 [ 0]
 [61]
 [ 0]
 [63]
 [ 0]
 [65]
 [ 0]
 [67]
 [ 0]
 [69]
 [ 0]
 [71]
 [ 0]
 [73]
 [ 0]
 [75]
 [ 0]
 [77]
 [ 0]
 [79]
 [ 0]
 [81]
 [ 0]
 [83]
 [ 0]
 [85]
 [ 0]
 [87]
 [ 0]
 [89]
 [ 0]
 [91]
 [ 0]
 [93]
 [ 0]
 [95]
 [ 0]
 [97]
 [ 0]
 [99]]


#### r)

In [177]:
import numpy as np

matrix1 = np.array([[0]])

for i in range(100):
    if(i!=0):
        matrix1 = np.r_[matrix1, [[i]]]

j = 1;
for i in range(101):
    if(j == 0):
        matrix1[j][0] = j
    if(i%2 == 0 and i!= 0):
        matrix1 = np.delete(matrix1, j, axis=0)
        j += 1
        
                
print(matrix1)

[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [20]
 [22]
 [24]
 [26]
 [28]
 [30]
 [32]
 [34]
 [36]
 [38]
 [40]
 [42]
 [44]
 [46]
 [48]
 [50]
 [52]
 [54]
 [56]
 [58]
 [60]
 [62]
 [64]
 [66]
 [68]
 [70]
 [72]
 [74]
 [76]
 [78]
 [80]
 [82]
 [84]
 [86]
 [88]
 [90]
 [92]
 [94]
 [96]
 [98]]


#### s)

In [178]:
import numpy as np

print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### t)

In [184]:
import numpy as np

matrix1 = np.array(([-11, 22, 33, 43, 77],
                   [11, 22, 33, -43, 77],
                   [11, 22, 33, 43, 77],
                   [11, 22, 33, 43, 77],
                   [11, -22, 33, 43, -77]))
for i in range(5):
    print(matrix1[i][i])
    
np.diag(matrix1)

-11
22
33
43
-77


array([-11,  22,  33,  43, -77])

#### u)

In [36]:
import numpy as np
import datetime

matrix1 =np.random.rand(1000,3)
matrix2 =np.random.rand(1000,3)
sk = [0,0,0]


startZeit = datetime.datetime.now()

print(matrix1)
for i in range(3):
    for j in range(1000):
        sk[i] += matrix1[j][i]*matrix2[j][i]

endZeit = datetime.datetime.now()
print(sk)
#Dauer Insgesamt
print("Zeit: ", endZeit - startZeit)

[[6.98631057e-01 5.95002377e-01 3.76164078e-02]
 [5.09081249e-01 5.85507622e-01 1.36089330e-01]
 [8.86863348e-01 5.32661731e-01 3.75927925e-01]
 ...
 [5.70677825e-01 1.07450446e-01 3.91640182e-01]
 [8.94971526e-01 6.66482305e-01 6.92450569e-02]
 [2.28676754e-01 6.29101135e-04 5.43354675e-01]]
[255.69752954686697, 238.07375328511986, 243.15539150163275]
Zeit:  0:00:00.002997


#### v)

 Für die Inverse einer $2x2$ Matrix $A = \begin{pmatrix}a_{11} & a_{12}\\a_{21} & a_{22}\end{pmatrix}$ gilt $A * A^{-1} = E = \begin{pmatrix} 1 & 0 \\ 0 & 1\end{pmatrix}$ sofern $ Det(A)!=0$ (sonst existiert keine Inverse.)
 
 
 $\Rightarrow A^{-1} = \begin{pmatrix}x_{11} & x_{12}\\x_{21} & x_{22}\end{pmatrix}$
 
 Nach Cramscher Regel gelten folgende Gleichungen für die Inverse:
 
 $x_{11} = \frac{1}{Det(A)}\cdot Det(\begin{pmatrix} 1 & a_{12} \\ 0 & a_{22}\end{pmatrix}) =  \frac{1}{Det(A)}\cdot a_{22}$
 
 $x_{12} = \frac{1}{Det(A)}\cdot Det(\begin{pmatrix} 0 & a_{12} \\ 1 & a_{22}\end{pmatrix}) =  \frac{1}{Det(A)}\cdot -a_{12}$
 
 $x_{21} = \frac{1}{Det(A)}\cdot Det(\begin{pmatrix} a_{11} & 1 \\ a_{21} & 0\end{pmatrix}) =  \frac{1}{Det(A)}\cdot -a_{21}$
 
 $x_{22} = \frac{1}{Det(A)}\cdot Det(\begin{pmatrix} a_{11} & 0 \\ a_{21} & 1\end{pmatrix}) =  \frac{1}{Det(A)}\cdot a_{11}$
 
 $\Rightarrow A^{-1} = \frac{1}{Det(A)} \cdot \begin{pmatrix} a_{22} & -a_{12} \\ -a_{21} & a_{12}\end{pmatrix}$  
 
 Daher folgende Berechnung ohne Schleifendurchlauf für die jeweiligen Matrizen!
 
 


In [88]:
# import numpy as np

matrix1 =np.random.randint(100, size=(1000,4))
matrixInversen = np.zeros([1000, 4], dtype=float)
determinanten = np.empty(1000, dtype=int)
invertierbar = np.empty(1000, dtype=bool)

for j in range(1000):
        determinanten[j] = matrix1[j][0] * matrix1[j][3] -  matrix1[j][1] * matrix1[j][2]
        if(determinanten[j] != 0):
            invertierbar[j] = True;
        else:
            invertierbar[j] = False;

print(matrix1)
print("!!__________________________________________________!!")
print(determinanten)


for j in range(1000):
    if(invertierbar[j] == True):
        matrixInversen[j][0] =   float(matrix1[j][3]/determinanten[j])
        print(matrix1[j][3], ":" , determinanten[j])
        matrixInversen[j][1] =    float(-matrix1[j][1]/determinanten[j])
        print(-matrix1[j][1], ":" ,  float(determinanten[j]))
        matrixInversen[j][2] =    float(-matrix1[j][2]/determinanten[j])
        print(-matrix1[j][2], ":" , determinanten[j])
        matrixInversen[j][3] =   matrix1[j][0]/determinanten[j]
        print(matrix1[j][0], ":" ,  float(determinanten[j]))

#Erste Matrix zum Überprüfen. Klappt soweit nur durch float nicht ganz genau!
print(matrix1[0])
print(matrixInversen[0])


    

[[63 43 97 74]
 [44 74 13  2]
 [ 8 50 12 84]
 ...
 [61  6 91 42]
 [10 11 25 70]
 [74 40 72 24]]
!!__________________________________________________!!
[  491  -874    72  1551  1440  -105 -1030 -4160  8084 -1949 -5744    16
    77  -938  4804   532  -572  1194 -2930  -402   980  -946   210 -1104
 -8004  2600   574 -4724 -2958   189  2631 -4232 -6933 -2162 -4599 -3747
   458  3715  -621 -1520  2414  1943 -3157  5532  2692   677  1049  1715
  -631  -441  2730  1555 -2742 -1632  -170   693   834  2810 -1507 -2000
 -1456    39   884  -282  3766 -4555  4182 -4737  6500  -240 -4230  -685
 -5676 -2324  6198  3825  1125  2106  1920 -1984  1508 -4292 -1126  3024
   365  -464 -1883   -72  1017   992  -344  1390   379   340  2688 -3796
  -948 -5398 -1668   388  2240  1352  4464  4286  -985 -3924 -4193  1733
  2536  -422  1534 -2090 -6906  1745  8381 -2086 -1960  5727  2930 -1403
   990  5779 -3224  -837   191   596 -1428  2358 -6868  1678 -1721   228
    39 -1234 -1997  6128   336  -540  5963 -44

# Aufgabe 3

In [124]:
import matplotlib.pyplot as plt

XWerte = np.random.randint(10, size=(20))
YWerte = np.empty(20, dtype=float)
for i in range(20):
    YWerte[i] = XWerte[i]*2
print(XWerte)
print(YWerte)
RauschWerte = np.random.normal(0, 1, YWerte.shape)
for i in range(20):
    YWerte[i] += RauschWerte[i]
print(YWerte)


[8 6 7 5 9 7 0 2 3 0 5 5 7 8 8 6 8 5 5 3]
[16. 12. 14. 10. 18. 14.  0.  4.  6.  0. 10. 10. 14. 16. 16. 12. 16. 10.
 10.  6.]
[1.59730727e+01 1.20673797e+01 1.40793956e+01 9.99719014e+00
 1.80204040e+01 1.40345112e+01 9.30078723e-03 3.86973417e+00
 6.03524541e+00 1.44864308e-02 1.00081959e+01 1.00861870e+01
 1.39712149e+01 1.60815929e+01 1.57556307e+01 1.18898049e+01
 1.60431965e+01 1.02220104e+01 1.00581752e+01 6.05181469e+00]
