In [1]:
import numpy as np
from numpy.linalg import eigh, eig
from math import sqrt


def ComputeSVD(A):
    """
       Given a matrix A use the eigen value decomposition to compute a SVD
       decomposition. It returns a tuple (U,Sigma,V) of np.matrix objects.
    """
    m, n = A.shape
    #B generieren
    B = np.matmul(A.transpose(), A)
    #Eigenwerte und Eigenvektoren generieren
    e ,ev = np.linalg.eig(B)
    print(B)
    print("________________")
    print(e)
    print("________________")
    print(ev)
    print("________________")
    
    #V generieren
    V = np.matrix(ev)
    
    #Sigma generieren
    
    singVal = np.sqrt(e)
    sig = np.diag(singVal)

    
    print("sig:")
    print(sig)
    print("________________")
 
        
    #U generieren
    U = np.zeros((m,0))
    for i in range(len(ev)):
        U = np.concatenate((U,(1 / singVal[i]) * A * ev[:,i]), axis=1)
    return U, sig, V# TODO: implement the function


def PseudoInverse(A):
    """
        Given a matrix A use the SVD of A to compute the pseudo inverse.
        It returns the pseudo inverse as a np.matrix object.
    """
    U, Sig, V = ComputeSVD(A)
    SigInv = np.linalg.inv(Sig)
    Utrans = np.transpose(U)       
    APsInv = V*SigInv*Utrans
    return APsInv # TODO: Implement the function


def LinearSolve(A, b):
    """
        Given a matrix A and a vector b this function solves the linear
        equations A*x=b by solving the least squares problem of minimizing
        |A*x-b| and returns the optimal x.
    """
    APsInv = PseudoInverse(A)
    return APsInv*b # TODO: Implement the function

In [2]:
if __name__ == "__main__":
    # Try the SVD decomposition
    A = np.matrix([ #1^i 2^i 3^i
        [1.0, 1.0, 1.0],
        [1.0, 2.0, 3.0],
        [1.0, 4.0, 9.0],
        [1.0, 8.0, 27.0]
    ])

    U, Sigma, V = ComputeSVD(A)
    print("U:")
    print(U)
    print("Sigma:")
    print(Sigma)
    print("V:")
    print(V)
    print("If the following numbers are nearly zero, SVD seems to be working.")
    print(np.linalg.norm(U * Sigma * V.H - A))
    print(np.linalg.norm(U.H * U - np.eye(3)))
    print(np.linalg.norm(V.H * V - np.eye(3)))
    # Try solving a least squares system
    b = np.matrix([1.0, 2.0, 3.0, 4.0]).T
    x = LinearSolve(A, b)
    print("If the following number is nearly zero, "
          "linear solving seems to be working.")
    print(np.linalg.norm(x - np.linalg.lstsq(A, b, rcond=None)[0]))

[[  4.  15.  40.]
 [ 15.  85. 259.]
 [ 40. 259. 820.]]
________________
[9.04118848e+02 1.82674982e-01 4.69847722e+00]
________________
[[-0.04734386 -0.7753102  -0.62980366]
 [-0.30193159  0.61212442 -0.73084951]
 [-0.95215328 -0.15555638  0.26307098]]
________________
sig:
[[30.0685691   0.          0.        ]
 [ 0.          0.42740494  0.        ]
 [ 0.          0.          2.16759711]]
________________
U:
[[-0.04328203 -0.74576154 -0.50635895]
 [-0.1166556  -0.0414841  -0.6007988 ]
 [-0.32673486  0.63915977 -0.546948  ]
 [-0.93688978 -0.18328554  0.28894516]]
Sigma:
[[30.0685691   0.          0.        ]
 [ 0.          0.42740494  0.        ]
 [ 0.          0.          2.16759711]]
V:
[[-0.04734386 -0.7753102  -0.62980366]
 [-0.30193159  0.61212442 -0.73084951]
 [-0.95215328 -0.15555638  0.26307098]]
If the following numbers are nearly zero, SVD seems to be working.
1.7390501704640538e-14
2.8372387606175682e-14
6.981760191221845e-15
[[  4.  15.  40.]
 [ 15.  85. 259.]
 [ 40. 259. 

In [110]:
 A = np.matrix([
        [1.0, 1.0, 1.0],
        [1.0, 2.0, 3.0],
        [1.0, 4.0, 9.0],
        [1.0, 8.0, 27.0]
    ])